import { useState } from 'react';
import { dbApi } from '@/api/db';
import { Node, Edge } from '@xyflow/react';
import { showToast } from '@/utils/ui';

type AppNode = Node & {
    data: {
        label: string;
        rows: number;
        columns?: any[];
    }
};

export function useDesignerExport(currentDb: string | null, nodes: Node[], edges: Edge[]) {
    const appNodes = nodes as AppNode[];
    const [exportFormat, setExportFormat] = useState<'sql' | 'laravel' | 'prisma' | 'typescript'>('sql');
    const [exportResult, setExportResult] = useState<string | null>(null);
    const [generating, setGenerating] = useState(false);

    const handleExport = async () => {
        if (!nodes.length) return;
        setGenerating(true);
        try {
            // Convert Nodes to SchemaTable standardized format
            const schemaTables: any[] = appNodes.map(n => ({
                name: n.data.label,
                columns: n.data.columns?.map((c: any) => ({
                    name: c[0],
                    type: c[1],
                    nullable: c[2] === 'YES',
                    key: c[3] === 'PRI' ? 'PRI' : (c[3] === 'UNI' ? 'UNI' : undefined),
                    default: c[4],
                    extra: c[5]
                })) || [],
                relations: edges.filter(e => e.source === n.id).map(e => ({
                        column: e.sourceHandle || 'id',
                        referencedTable: appNodes.find(rn => rn.id === e.target)?.data.label || e.target,
                        referencedColumn: e.targetHandle || 'id'
                }))
            }));

            let result = '';

            if (exportFormat === 'sql') {
                const promises = nodes.map(n => dbApi.getCreateTable(currentDb!, n.id));
                const sqls = await Promise.all(promises);
                result = `-- Schema Export for ${currentDb}\n-- Generated by OmniMIN\n\n` + sqls.join(';\n\n') + ';';
            } 
            else if (exportFormat === 'laravel') {
                const { LaravelGenerator } = await import('@/generators/laravel');
                result = schemaTables.map(t => 
                    `// Migration: ${t.name}\n` + LaravelGenerator.generateMigration(t) + "\n\n" + 
                    `// Model: ${t.name}\n` + LaravelGenerator.generateModel(t)
                ).join('\n\n// --------------------------------------------------------\n\n');
            }
            else if (exportFormat === 'typescript') {
                const { TypescriptGenerator } = await import('@/generators/typescript');
                result = schemaTables.map(t => TypescriptGenerator.generateInterface(t)).join('\n\n');
            }
            else if (exportFormat === 'prisma') {
                const { PrismaGenerator } = await import('@/generators/prisma');
                result = schemaTables.map(t => PrismaGenerator.generateModel(t)).join('\n\n');
            }

            setExportResult(result);
        } catch (e) {
            console.error(e);
            showToast("Failed to generate export", 'error');
        } finally {
            setGenerating(false);
        }
    };

    return {
        exportFormat,
        setExportFormat,
        exportResult,
        setExportResult,
        generating,
        handleExport
    };
}
