import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Download, Loader2, Database, Copy, CheckCircle } from 'lucide-react';
import { useAppStore } from '@/stores/useAppStore';
import { dbApi } from '@/api/db';
import { showToast } from '@/utils/ui';

export function Export() {
    const { currentDb } = useAppStore();
    const [format, setFormat] = useState<'sql' | 'laravel' | 'prisma' | 'typescript'>('sql');
    const [generating, setGenerating] = useState(false);
    const [result, setResult] = useState<string | null>(null);

    // Fetch Tables for selection (optional enhancement: select tables)
    const { data: tables } = useQuery({
        queryKey: ['tables', currentDb],
        queryFn: () => dbApi.getTables(currentDb!),
        enabled: !!currentDb
    });

    const handleGenerate = async () => {
        if (!tables || !currentDb) return;
        setGenerating(true);
        setResult(null);

        try {
            // 1. Fetch Schema for ALL tables
            const promises = tables.map(async t => {
                const res = await dbApi.executeQuery(currentDb, `SHOW COLUMNS FROM \`${t.name}\``);
                return {
                    name: t.name,
                    columns: res.rows ? res.rows.map((r: any[]) => ({
                        name: r[0],
                        type: r[1],
                        nullable: r[2] === 'YES',
                        key: r[3] === 'PRI' ? 'PRI' : (r[3] === 'UNI' ? 'UNI' : undefined),
                        default: r[4],
                        extra: r[5]
                    })) : [],
                    relations: [] // TODO: Fetch relations if needed for Prisma/Laravel (Currently doing basic mapping)
                };
            });

            const schemaTables = await Promise.all(promises);

            // 2. Fetch Relations (Bulk)
            const relRes = await dbApi.getRelations(currentDb);
            const allRelations = relRes.rows || [];
            
            // Map relations to tables
            schemaTables.forEach(t => {
                t.relations = allRelations
                    .filter((r: any[]) => r[0] === t.name)
                    .map((r: any[]) => ({
                        column: r[1],
                        referencedTable: r[2],
                        referencedColumn: r[3]
                    }));
            });

            // 3. Generate Code
            let output = '';
            
            if (format === 'sql') {
                const createPromises = tables.map(t => dbApi.getCreateTable(currentDb, t.name));
                const sqls = await Promise.all(createPromises);
                output = `-- Export for ${currentDb}\n-- Generated by LuminaSQL\n\n` + sqls.join(';\n\n') + ';';
            } 
            else if (format === 'laravel') {
                const { LaravelGenerator } = await import('@/generators/laravel');
                output = schemaTables.map(t => 
                    `// Migration: ${t.name}\n` + LaravelGenerator.generateMigration(t) + "\n\n" + 
                    `// Model: ${t.name}\n` + LaravelGenerator.generateModel(t)
                ).join('\n\n// --------------------------------------------------------\n\n');
            }
            else if (format === 'typescript') {
                const { TypescriptGenerator } = await import('@/generators/typescript');
                output = schemaTables.map(t => TypescriptGenerator.generateInterface(t)).join('\n\n');
            }
            else if (format === 'prisma') {
                const { PrismaGenerator } = await import('@/generators/prisma');
                output = schemaTables.map(t => PrismaGenerator.generateModel(t)).join('\n\n');
            }

            setResult(output);
            showToast('Export generated successfully', 'success');

        } catch (e) {
            console.error(e);
            showToast('Failed to generate export', 'error');
        } finally {
            setGenerating(false);
        }
    };

    if (!currentDb) return <div className="p-12 text-center opacity-50">Select a database</div>;

    return (
        <div className="p-8 max-w-6xl mx-auto h-full flex flex-col">
            <div className="mb-8 flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-bold flex items-center gap-3">
                        <Database className="text-blue-400" /> 
                        Export Database
                    </h1>
                    <p className="text-white/40 mt-1">Generate code, migrations, or SQL dumps for <span className="text-blue-200 font-mono">{currentDb}</span></p>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-8 flex-1 overflow-hidden">
                {/* Options Panel */}
                <div className="glass-panel p-6 flex flex-col gap-6 h-fit">
                    <div>
                        <label className="block text-xs uppercase tracking-wider text-white/50 mb-3 font-bold">Export Format</label>
                        <div className="flex flex-col gap-2">
                            {[
                                { id: 'sql', label: 'SQL Dump', desc: 'CREATE TABLE statements' },
                                { id: 'laravel', label: 'Laravel', desc: 'Migrations & Models' },
                                { id: 'typescript', label: 'TypeScript', desc: 'Interfaces' },
                                { id: 'prisma', label: 'Prisma', desc: 'Schema Models' },
                            ].map(opt => (
                                <button
                                    key={opt.id}
                                    onClick={() => setFormat(opt.id as any)}
                                    className={`p-3 rounded text-left border transition-all ${
                                        format === opt.id 
                                        ? 'bg-blue-600/20 border-blue-500/50 text-white shadow-[0_0_15px_rgba(59,130,246,0.2)]' 
                                        : 'bg-white/5 border-transparent hover:bg-white/10 text-white/70'
                                    }`}
                                >
                                    <div className="font-bold text-sm">{opt.label}</div>
                                    <div className="text-xs opacity-60 mt-0.5">{opt.desc}</div>
                                </button>
                            ))}
                        </div>
                    </div>

                    <div className="mt-4">
                        <button 
                            onClick={handleGenerate}
                            disabled={generating}
                            className="w-full btn-primary py-3 flex justify-center items-center gap-2"
                        >
                            {generating ? <Loader2 className="animate-spin" /> : <Download size={18} />}
                            {generating ? 'Generating...' : 'Generate Export'}
                        </button>
                    </div>
                </div>

                {/* Result Panel */}
                <div className="md:col-span-3 h-full flex flex-col glass-panel overflow-hidden relative">
                    {!result ? (
                        <div className="flex-1 flex flex-col items-center justify-center opacity-30">
                            <Download size={64} strokeWidth={1} />
                            <p className="mt-4 text-lg">Select a format and click Generate</p>
                        </div>
                    ) : (
                        <>
                            <div className="p-3 border-b border-white/10 flex justify-between items-center bg-white/5">
                                <span className="font-mono text-xs opacity-50">{new Date().toLocaleString()} • {format.toUpperCase()}</span>
                                <button 
                                    onClick={() => { navigator.clipboard.writeText(result); showToast('Copied to clipboard'); }}
                                    className="text-xs flex items-center gap-1.5 hover:text-white text-blue-300 transition-colors"
                                >
                                    <Copy size={14} /> Copy to Clipboard
                                </button>
                            </div>
                            <div className="flex-1 overflow-auto p-6 bg-[#0B0E14]">
                                <pre className="font-mono text-sm text-blue-100/90 whitespace-pre-wrap selection:bg-blue-500/30">{result}</pre>
                            </div>
                        </>
                    )}
                </div>
            </div>
        </div>
    );
}
