import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Download, Loader2, Database, Copy, CheckCircle } from 'lucide-react';
import { useAppStore } from '@/stores/useAppStore';
import { dbApi } from '@/api/db';
import { showToast } from '@/utils/ui';

export function Export() {
    const { currentDb } = useAppStore();
    const [format, setFormat] = useState<'sql' | 'laravel' | 'prisma' | 'typescript'>('sql');
    const [generating, setGenerating] = useState(false);
    const [result, setResult] = useState<string | null>(null);

    // Fetch Tables for selection (optional enhancement: select tables)
    const { data: tables } = useQuery({
        queryKey: ['tables', currentDb],
        queryFn: () => dbApi.getTables(currentDb!),
        enabled: !!currentDb
    });

    const handleGenerate = async () => {
        if (!tables || !currentDb) return;
        setGenerating(true);
        setResult(null);

        try {
            // 1. Fetch Schema for ALL tables
            const promises = tables.map(async t => {
                const res = await dbApi.executeQuery(currentDb, `SHOW COLUMNS FROM \`${t.name}\``);
                return {
                    name: t.name,
                    columns: res.rows ? res.rows.map((r: any[]) => ({
                        name: r[0],
                        type: r[1],
                        nullable: r[2] === 'YES',
                        key: r[3] === 'PRI' ? 'PRI' : (r[3] === 'UNI' ? 'UNI' : undefined),
                        default: r[4],
                        extra: r[5]
                    })) : [],
                    relations: [] // TODO: Fetch relations if needed for Prisma/Laravel (Currently doing basic mapping)
                };
            });

            const schemaTables = await Promise.all(promises);

            // 2. Fetch Relations (Bulk)
            const relRes = await dbApi.getRelations(currentDb);
            const allRelations = relRes.rows || [];
            
            // Map relations to tables
            schemaTables.forEach(t => {
                t.relations = allRelations
                    .filter((r: any[]) => r[0] === t.name)
                    .map((r: any[]) => ({
                        column: r[1],
                        referencedTable: r[2],
                        referencedColumn: r[3]
                    }));
            });

            // 3. Generate Code
            let output = '';
            
            if (format === 'sql') {
                const createPromises = tables.map(t => dbApi.getCreateTable(currentDb, t.name));
                const sqls = await Promise.all(createPromises);
                output = `-- Export for ${currentDb}\n-- Generated by OmniMIN\n\n` + sqls.join(';\n\n') + ';';
            } 
            else if (format === 'laravel') {
                const { LaravelGenerator } = await import('@/generators/laravel');
                output = schemaTables.map(t => 
                    `// Migration: ${t.name}\n` + LaravelGenerator.generateMigration(t) + "\n\n" + 
                    `// Model: ${t.name}\n` + LaravelGenerator.generateModel(t)
                ).join('\n\n// --------------------------------------------------------\n\n');
            }
            else if (format === 'typescript') {
                const { TypescriptGenerator } = await import('@/generators/typescript');
                output = schemaTables.map(t => TypescriptGenerator.generateInterface(t)).join('\n\n');
            }
            else if (format === 'prisma') {
                const { PrismaGenerator } = await import('@/generators/prisma');
                output = schemaTables.map(t => PrismaGenerator.generateModel(t)).join('\n\n');
            }

            setResult(output);
            showToast('Export generated successfully', 'success');

        } catch (e) {
            console.error(e);
            showToast('Failed to generate export', 'error');
        } finally {
            setGenerating(false);
        }
    };

    if (!currentDb) return <div className="p-12 text-center opacity-50">Select a database</div>;

    return (
        <div className="p-8 max-w-4xl mx-auto flex flex-col gap-6 h-full">
            <div className="glass-panel p-6">
                <h2 className="text-xl font-bold flex items-center gap-2 mb-2 text-text-main">
                    <Database className="text-primary" /> 
                    Export Database
                </h2>
                <p className="text-text-muted mt-1">Generate code, migrations, or SQL dumps for <span className="text-primary font-mono">{currentDb}</span></p>
            </div>

            <div className="grid grid-cols-2 gap-8 flex-1 min-h-0">
                <div className="flex flex-col gap-6">
                    {/* Format Selection */}
                    <div className="glass-panel p-6">
                    <label className="block text-xs uppercase tracking-wider text-text-muted mb-3 font-bold">Export Format</label>
                    <div className="grid grid-cols-2 gap-3">
                        {['sql', 'json', 'csv', 'php'].map(f => (
                            <button
                                key={f}
                                onClick={() => setFormat(f as any)}
                                className={`
                                    p-3 rounded-lg border text-sm font-bold uppercase tracking-wide transition-all
                                    ${format === f 
                                    ? 'bg-primary/20 border-primary/50 text-text-main shadow-[0_0_15px_var(--color-primary-glow)]' 
                                    : 'bg-surface border-transparent hover:bg-hover-bg text-text-muted'}
                                `}
                            >
                                {f}
                            </button>
                        ))}
                    </div>
                    </div>

                    <div className="mt-4">
                        <button 
                            onClick={handleGenerate}
                            disabled={generating}
                            className="w-full btn-primary py-3 flex justify-center items-center gap-2"
                        >
                            {generating ? <Loader2 className="animate-spin" /> : <Download size={18} />}
                            {generating ? 'Generating...' : 'Generate Export'}
                        </button>
                    </div>
                </div>

                {/* Result Panel */}
                <div className="glass-panel flex flex-col h-full overflow-hidden border-border bg-surface">
                    {!result ? (
                        <div className="flex-1 flex flex-col items-center justify-center opacity-30">
                            <Download size={64} strokeWidth={1} />
                            <p className="mt-4 text-lg">Select a format and click Generate</p>
                        </div>
                    ) : (
                        <>
                            <div className="p-3 border-b border-border flex justify-between items-center bg-canvas">
                                <span className="text-xs font-bold uppercase tracking-wider text-text-muted">Preview</span>
                                <div className="flex gap-2">
                                    <button 
                                        onClick={() => { navigator.clipboard.writeText(result); showToast('Copied to clipboard'); }}
                                        className="text-xs flex items-center gap-1.5 hover:text-text-main text-primary transition-colors"
                                    >
                                        <Copy size={14} /> Copy to Clipboard
                                    </button>
                                </div>
                            </div>
                            <div className="flex-1 overflow-auto p-6 bg-canvas">
                                <pre className="font-mono text-sm text-text-main whitespace-pre-wrap selection:bg-primary/30">{result}</pre>
                            </div>
                        </>
                    )}
                </div>
            </div>
        </div>
    );
}
